# Use an official lightweight Node.js image
FROM node:alpine

# Set the working directory in the container
WORKDIR /app

COPY api/package*.json ./

RUN npm install

# Copy the current directory contents into the container at /app
COPY api/api.js .

# Make port 3000 available to the world outside this container
EXPOSE 3000

# Run api.js when the container launches
CMD ["node", "api.js"]