version: '3'

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "8080:80"
    networks:
      - bigbucks
    depends_on:
      - html
      - api

  html:
    build:
      context: .
      dockerfile: Dockerfile.html
    volumes:
      - ./html:/usr/share/nginx/html
    networks:
      - bigbucks
  
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "3000:3000"
    networks:
      - bigbucks

networks:
  bigbucks:
    driver: bridge
